### ISSUE TITLE
can you give me more example? 

### ISSUE THREAD

**Issue by Rock-liyi** [berty/go-ipfs-log#51]
I would like to use go-ipfs-log, but   do not know  how use it . 
so can you give me more example?

**Comment by glouvigny** [comment]
Hi, `go-ipfs-log` is a low level library used by `[go-orbit-db](https://github.com/berty/go-orbit-db)`, you might want to use it instead.

Otherwise you can also read the tests files to know how to use it.

If that does not help you can you tell me why you would use `go-ipfs-log` instead of `go-orbit-db`, and an example that would help you?

**Comment by Rock-liyi** [comment]
I 'm going to build a database    similar  orbit-db ,but only use golang  language.  
I think  that will  not satisfied every one , if  orbit-db  only use javascript to build a database

**Comment by glouvigny** [comment]
I think you mix [go-orbit-db](https://github.com/berty/go-orbit-db) which is fully written in Go and that uses go-ipfs-log and [orbit-db] the original JavaScript version.
